-- Add week columns and calculations to lesson_monitoring table
ALTER TABLE lesson_monitoring
ADD COLUMN week1 INT DEFAULT 0 AFTER term,
ADD COLUMN week2 INT DEFAULT 0 AFTER week1,
ADD COLUMN week3 INT DEFAULT 0 AFTER week2,
ADD COLUMN week4 INT DEFAULT 0 AFTER week3,
ADD COLUMN week5 INT DEFAULT 0 AFTER week4,
ADD COLUMN week6 INT DEFAULT 0 AFTER week5,
ADD COLUMN week7 INT DEFAULT 0 AFTER week6,
ADD COLUMN week8 INT DEFAULT 0 AFTER week7,
ADD COLUMN week9 INT DEFAULT 0 AFTER week8,
ADD COLUMN week10 INT DEFAULT 0 AFTER week9,
ADD COLUMN week11 INT DEFAULT 0 AFTER week10,
ADD COLUMN week12 INT DEFAULT 0 AFTER week11,
ADD COLUMN week13 INT DEFAULT 0 AFTER week12,
ADD COLUMN single_lessons_lost INT DEFAULT 0 AFTER week13,
ADD COLUMN double_lessons_lost INT DEFAULT 0 AFTER single_lessons_lost;
