-- Add weekly and academic fields to class_teacher_performance table
ALTER TABLE class_teacher_performance
ADD COLUMN roll_call INT DEFAULT 0 AFTER stream,
ADD COLUMN mentorship INT DEFAULT 0 AFTER roll_call,
ADD COLUMN devotion INT DEFAULT 0 AFTER mentorship,
ADD COLUMN cleanliness INT DEFAULT 0 AFTER devotion,
ADD COLUMN parents_contacted INT DEFAULT 0 AFTER cleanliness,
ADD COLUMN bt1 DECIMAL(10,2) DEFAULT 0 AFTER parents_contacted,
ADD COLUMN t1 DECIMAL(10,2) DEFAULT 0 AFTER bt1,
ADD COLUMN t2 DECIMAL(10,2) DEFAULT 0 AFTER t1,
ADD COLUMN t3 DECIMAL(10,2) DEFAULT 0 AFTER t2,
ADD COLUMN c1 DECIMAL(10,2) DEFAULT 0 AFTER t3,
ADD COLUMN c2 DECIMAL(10,2) DEFAULT 0 AFTER c1,
ADD COLUMN c3 DECIMAL(10,2) DEFAULT 0 AFTER c2,
ADD COLUMN average_score DECIMAL(10,2) DEFAULT 0 AFTER c3,
ADD COLUMN average_comment VARCHAR(255) DEFAULT '' AFTER average_score;
